swagger: '2.0'
info:
  version: 1.0.0
  title: Coffee
paths:
  /coffee:
    post:
      tags:
      - coffee
      summary: Add a new coffee to the store
      operationId: addCoffee
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      parameters:
      - in: body
        name: body
        description: Coffee object that needs to be added to the store
        required: true
        schema:
          $ref: '#/definitions/Coffee'
      responses:
        405:
          description: Invalid input
    put:
      tags:
      - coffee
      summary: Update an existing coffee
      operationId: updateCoffee
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      parameters:
      - in: body
        name: body
        description: Coffee object that needs to be added to the store
        required: true
        schema:
          $ref: '#/definitions/Coffee'
      responses:
        400:
          description: Invalid ID supplied
        404:
          description: Coffee not found
        405:
          description: Validation exception
  /coffee/{coffeeId}:
    get:
      tags:
      - coffee
      summary: Find pet by ID
      description: Returns a single coffee
      operationId: getCoffeeById
      produces:
      - application/json
      - application/xml
      parameters:
      - name: coffeeId
        in: path
        description: ID of coffee to return
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Coffee'
        400:
          description: Invalid ID supplied
        404:
          description: Coffee not found
    post:
      tags:
      - coffee
      summary: Updates a coffee in the store with form data
      operationId: updateCoffeeWithForm
      consumes:
      - application/x-www-form-urlencoded
      produces:
      - application/json
      - application/xml
      parameters:
      - name: coffeeId
        in: path
        description: ID of coffee that needs to be updated
        required: true
        type: integer
        format: int64
      - name: name
        in: formData
        description: Updated name of the coffee
        required: false
        type: string
      - name: status
        in: formData
        description: Updated status of the coffee
        required: false
        type: string
      responses:
        405:
          description: Invalid input
    delete:
      tags:
      - coffee
      summary: Deletes a coffee
      operationId: deleteCoffee
      produces:
      - application/json
      - application/xml
      parameters:
      - name: api_key
        in: header
        required: false
        type: string
      - name: coffeeId
        in: path
        description: Coffee id to delete
        required: true
        type: integer
        format: int64
      responses:
        400:
          description: Invalid ID supplied
        404:
          description: Coffee not found
definitions:
  Coffee:
    type: object
    required:
    - name
    - ingredients
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      ingredients:
        type: array
        items:
          type: string
      preparation:
        type: string
host: virtserver.swaggerhub.com
basePath: /zscseh93/Coffee/1.0.0
schemes:
 - https
 - http